# Generated by Django 3.0.7 on 2021-12-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20211215_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='milage',
            new_name='kilometers',
        ),
    ]
