# Generated by Django 3.0.7 on 2021-12-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20211215_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Cairo', 'Cairo'), ('Dakahlia', 'Dakahlia'), ('Damietta', 'Damietta'), ('Fayoum', 'Fayoum'), ('Gharbia', 'Gharbia'), ('Giaz', 'Giza'), ('Ismailia', 'Ismailia'), ('Kafr al-Sheikh', 'Kafr al-Sheikh'), ('Luxor', 'Luxor'), ('Matruh', 'Matruh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley'), ('Port Said', 'Port Said'), ('Qalyubia', 'Qalyubia'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sharqia', 'Sharqia'), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Suez', 'Suez')], max_length=100),
        ),
    ]
