# Generated by Django 3.0.7 on 2021-12-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20211215_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='if_featured',
            new_name='is_featured',
        ),
    ]
