# Generated by Django 3.0.7 on 2021-12-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20211215_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
