# Generated by Django 3.0.7 on 2021-12-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, choices=[('Alfa Romeo ', 'Alfa Romeo '), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Bentley', 'Bentley'), ('Bugatti', 'Bugatti'), ('Cadillac', 'Cadillac'), ('Changan', 'Changan'), ('Chery', 'Chery'), ('Chevrolet ', 'Chevrolet '), ('Chrysler ', 'Chrysler '), ('Daihatsu', 'Daihatsu'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('GAC', 'GAC'), ('GMC', 'GMC'), ('Geely', 'Geely'), ('Genesis', 'Genesis'), ('Honda', 'Honda'), ('Hummer', 'Hummer'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Isuzu', 'Isuzu'), ('JAC', 'JAC'), ('Jaguar ', 'Jaguar '), ('Jeep ', 'Jeep '), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('MG', 'MG'), ('MINI', 'MINI'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('Mazda', 'Mazda'), ('Mclaren', 'Mclaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mercury', 'Mercury'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Proton', 'Proton'), ('Range Rover', 'Range Rover'), ('Renault', 'Renault'), ('Rolls Royce', 'Rolls Royce'), ('Seat', 'Seat'), ('Skoda', 'Skoda'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Zotye', 'Zotye'), ('Wiesmann', 'Wiesmann')], max_length=50),
        ),
    ]
